# Generated by Django 3.1.7 on 2021-03-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210302_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yapilan_yorum', models.TextField()),
                ('yorum_olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yorum_duzenlenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yazan_kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to=settings.AUTH_USER_MODEL)),
                ('yazilan_icerik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='blog.yazilarmodel')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'yorumlar',
                'db_table': 'yorum',
            },
        ),
    ]
