# Generated by Django 3.1.7 on 2021-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210303_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iletisimmodel',
            old_name='iletisim_olusturulma_tarihi',
            new_name='olusturulma_tarihi',
        ),
        migrations.AddField(
            model_name='iletisimmodel',
            name='duzenleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
